travis:
  secure:
    BINSTAR_TOKEN: YRXexEJKkZH6jql2TuU2uSNhkNfQyRm/wNC0q1IlUlYdKWfdn45riJ2ymX2autcSbA2knfQUIUsB1QWc524j0XSe/hhHLsm3siVnJOudJiKur6TzAYR77+9svhBQCPTvnIU+xyW22UDBouQllfV00PSH+zb0RARZdaeyI0PZ4h+pMXQayMMlCJvgCTGueKSYsVnPPGvrHKJnu2Uj/RVlCDzu1HgCgGSLnjwyZoU4s1WMYtGF6we5xW1tniJ/UiEwPNu8/r2K6O2CC0M6wp3YdPQlFNiwxNqPsvvS9qBR+Qt4pK5FsMKdNA5JdR8ZUJCGPjRatQsMXTjGLTc8co5NkrLBrpXHGo2lNklQgbFJQvGtaCA0UzwkXYzsWJdhy9B4GORfCVJKvuJxJ8dFbM4crt3o/Vgf7HAq5cTSXklQ15nVFniCOYrZ/afyZXbXTvYOcPuPQL7ySfv8M787Vtmz/YuctMDkco19lheK/2BQMlTSENNEDKDzQiYK+bMSDpIatoJeLxXz3lamJOJzfVI0xEKNnhHl3nUkjeoiRCqoDIA9QDX9bXrtTog1O0n/rBG+vj93Um1UgkPdL2r3ftRoxQFugY7DJpTI6m2lw51UUMlEkBKgmr4Jh2xKr9EYck0hKd6eg3KcMSAFVhV0qmOPLKmk2b4XmbFHAoDRoH/t0tU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
